#!/bin/sh

rootdir="$(pwd)"
bindir="$rootdir/build/bin"
outdir="$rootdir/test/bench"
tmpdir="/tmp"


tests=$(find "$rootdir/test" -name "*.qasp" -printf "%s %p\n" | sort -n | sed 's/^[0-9]* //')

time="/usr/bin/time --format='%e'"








echo "|Test|QASP|QASP (C)|QASP (A)|DEMACS|"
echo "|----|----|--------|--------|------|"


for test in $tests; do

    # Run QASP
    echo "Running $test" 1>&2

    r1=`($time $bindir/qasp -t 600 -q    "$test"                                             2>&1 > /dev/null) | tail -n1 | tr -d "'"`
    r2=`($time $bindir/qasp -t 600 -q -c "$test"                                             2>&1 > /dev/null) | tail -n1 | tr -d "'"`
    r3=`($time $bindir/qasp -t 600 -q -l "$test"                                             2>&1 > /dev/null) | tail -n1 | tr -d "'"`
    r4=`($time timeout 600 java -jar $rootdir/extra/demacs/qasp-0.1.jar "$test"              2>&1 > /dev/null) | tail -n1 | tr -d "'"`

    echo "|$(basename $test .qasp)|$r1|$r2|$r3|$r4|"

done


