set(CPACK_GENERATOR             "TGZ;TXZ;ZIP")
set(CPACK_SOURCE_GENERATOR      "TGZ;TXZ;ZIP")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README  "${CMAKE_SOURCE_DIR}/README.md")

set(CPACK_PACKAGE_NAME                  "${CMAKE_PROJECT_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_FILE      "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY   "${CMAKE_PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_EXECUTABLES           "qasp")
set(CPACK_PACKAGE_INSTALL_DIRECTORY     "QASP")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY  "QASP")
set(CPACK_PACKAGE_VENDOR                "kwrx")
set(CPACK_PACKAGE_CONTACT               "Antonino Natale")

set(CPACK_DEBIAN_PACKAGE_HOMEPAGE       "${CMAKE_PROJECT_HOMEPAGE_URL}")
set(CPACK_DEBIAN_PACKAGE_DEPENDS        "libboost-dev (>= 1.74.0.3)")

