name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      working-directory: ${{github.workspace}}
      run: sudo apt update && sudo apt install libboost-dev ninja-build

    - name: Create Build Environment (Debug)
      run: cmake -E make_directory ${{github.workspace}}/debug

    - name: Create Build Environment (Release)
      run: cmake -E make_directory ${{github.workspace}}/release

    - name: Configure CMake (Debug)
      shell: bash
      working-directory: ${{github.workspace}}/debug
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -G Ninja

    - name: Configure CMake (Release)
      shell: bash
      working-directory: ${{github.workspace}}/release
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build (Debug)
      working-directory: ${{github.workspace}}/debug
      shell: bash
      run: cmake --build . --config Debug -j 8

    - name: Build (Release)
      working-directory: ${{github.workspace}}/release
      shell: bash
      run: cmake --build . --config Release -j 8

    - name: Test (Debug)
      working-directory: ${{github.workspace}}/debug
      shell: bash
      run: ctest -C Debug --rerun-failed --output-on-failure

    - name: Test (Release)
      working-directory: ${{github.workspace}}/release
      shell: bash
      run: ctest -C Release --rerun-failed --output-on-failure
      
