name: CMake Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C Release

    - name: Install Dependencies
      working-directory: ${{github.workspace}}
      shell: bash
      run: sudo apt update && sudo apt install dpkg rpm

    - name: Package
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C Release .
      
    - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{github.workspace}}/build/qasp-*.deb
            ${{github.workspace}}/build/qasp-*.rpm
            ${{github.workspace}}/build/qasp-*.tar.gz
            ${{github.workspace}}/build/qasp-*.tar.xz
            ${{github.workspace}}/build/qasp-*.zip
